# Generated by Django 4.0 on 2023-05-30 14:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ингредиента', max_length=200, verbose_name='Ингредиент')),
                ('measurement_unit', models.CharField(help_text='Единица измерения', max_length=10, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientForRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Значение должно быть больше 1', validators=[django.core.validators.MinValueValidator(1)])),
                ('ingredient', models.ForeignKey(help_text='Ингредиент в рецепте', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='ingredients.ingredient', verbose_name='Ингредиент в рецепте')),
            ],
        ),
    ]
