# Generated by Django 2.2.28 on 2023-06-02 20:26

from django.db import migrations, models
import tags.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20230602_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Цвет для тега', max_length=7, validators=[tags.validators.validate_hex], verbose_name='Цвет для тега'),
        ),
    ]
