version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env   

  frontend:
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    image: kvazymir1199/foodgramm_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  backend:
    # build:
    #   context:  ../backend/foodgramm
    #   dockerfile: Dockerfile
    image: kvazymir1199/foodgramm_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - /data:/app/data/
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - backend
      
volumes:
  static_value:
  media_value:
  db_data:
  data:
