# Generated by Django 3.2 on 2023-06-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopingcard',
            options={'verbose_name': 'список покупок'},
        ),
        migrations.AddConstraint(
            model_name='shopingcard',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shopping_card_recipe'),
        ),
    ]
