# Generated by Django 3.2 on 2023-06-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20230601_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopingcard',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
