name: foodgram_react_project_workflow

on: [push]

jobs:
  
  
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    # needs: tests
    if: github.ref_name == 'master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push backend image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kvazymir1199/foodgramm_backend:latest
          context: backend/foodgramm/

      - name: Push frontend image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kvazymir1199/foodgramm_frontend:latest
          context: frontend/

